# Generated by Django 5.2.1 on 2025-05-20 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_available_product_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='images',
        ),
    ]
