# Generated by Django 5.2.1 on 2025-05-20 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_image_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
